[package]
name = "mlar"
description = "A wrapper around the MLA library for common usecases"
version = "1.0.0"
authors = ["Camille Mougey <camille.mougey@ssi.gouv.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
glob = "0.3"
mla = { path = "../mla" }
curve25519-parser = { path = "../curve25519-parser" }
rand = "0.7"
x25519-dalek = "1"
humansize = "1"
hex = "0.4"
# Could be made optional / feature to enable (for binary size)
tar = "0.4"
rand_chacha = "0.2"

[dev-dependencies]
assert_cmd = "1.0"
assert_fs = "1.0"
permutate = "0.3"
