[package]
name = "mla"
version = "1.0.0"
authors = ["Camille Mougey <camille.mougey@ssi.gouv.fr>"]
edition = "2018"
license = "LGPL-3.0-only"
description = "Multi Layer Archive - A pure rust encrypted and compressed archive file format"
homepage = "https://github.com/ANSSI-FR/MLA"
repository = "https://github.com/ANSSI-FR/MLA"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
rand_chacha = "0.2"
brotli = "3.3"
aes-ctr = "0"
bitflags = "1.2"
byteorder = "1.3"
serde = { version = "1", features = ["derive"] }
bincode = "~1.2"
# Crypto needs
# Version fixed due to avoid conflict dependencies with `aes`, `aes-ctr` and `ghash`
generic-array = "0.14"
ghash = "0"
aes = "0"
subtle = "2"
digest = "0"
# ECC
x25519-dalek = "1"
hkdf = "0"
sha2 = "0"
zeroize = "1"

[dev-dependencies]
hex-literal = "0.3"
aes-gcm = "0"
aead = "0"
criterion = "0.3"
curve25519-parser = { path = "../curve25519-parser" }
hex = "0.4"

[[bench]]
name = "bench_archive"
harness = false
